document.write('<object id="TANGER_OCX" classid="clsid:' + 'A39F1330-3322-4a1d-9BF0-0BA2BB90E970' + '" ')
document.write('codebase="./ntko/OfficeControl.cab#version=5,0,3,1" width="100%" height="100%">   ')
document.write('<param name="IsUseUTF8URL" value="-1">   ')
document.write('<param name="IsUseUTF8Data" value="-1">   ')
document.write('<param name="BorderStyle" value="1">   ')
document.write('<param name="BorderColor" value="14402205">   ')
document.write('<param name="TitlebarColor" value="15658734">   ')
document.write('<param name="TitlebarTextColor" value="0">   ')
document.write('<param name="MenubarColor" value="13158600">   ')
document.write('<param name="MenuButtonColor" VALUE="16180947">   ')
document.write('<param name="MenuBarStyle" value="3">   ')
document.write('<param name="MenuButtonStyle" value="7">   ')
document.write('<param name="WebUserName" value="NTKO">   ')
document.write('<param name="UILangCode" value="AUTO">   ')
document.write('<param name="Serverpage" value="paaa.asp">   ')
document.write('<param name="Caption" value="测试">   ')
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。请点击<a href="">安装控件</a></SPAN>   ')
document.write("</object>")
